name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Baixar variáveis de ambiente da Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir aplicação
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Fazer deploy para produção
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}